from pathlib import Path
from typing import Any, Callable, ClassVar, Generic, Protocol, TypeAlias, TypeVar, overload

class PyHandlebarsError(Exception): ...
class TemplateParseError(PyHandlebarsError): ...
class FormatError(PyHandlebarsError): ...
class HelperError(PyHandlebarsError): ...

class ModelDumpable(Protocol):
    def model_dump(self) -> dict: ...

T = TypeVar("T", bound=ModelDumpable | dict)
F = TypeVar("F", bound=Callable[[HelperParameter, Context], str])

HelperParameter: TypeAlias = list[str]
Context: TypeAlias = dict

class _HelperDescriptor:
    @overload
    def __call__(self, func: F) -> F: ...
    @overload
    def __call__(self, name: str | None = None) -> Callable[[F], F]: ...
    @overload
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class PyHandlebars:
    def __init__(self, strict_mode: bool = False, dev_mode: bool = False) -> None: ...
    def register_helper(self, name: str, func: Callable[[HelperParameter, Context], str]) -> None: ...
    helper: ClassVar[_HelperDescriptor]

class Template(Generic[T]):
    def __init__(self, template: str, name: str | None = None, client: PyHandlebars | None = None) -> None: ...
    def format(self, data: T) -> str: ...
    @classmethod
    def from_file(cls, path: str | Path, client: PyHandlebars | None = None) -> "Template[T]": ...
